version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codefolio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Registry Server (Eureka)
  registry-server:
    build: 
      context: ./registryServer
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Config Server
  config-server:
    build: 
      context: ./configServer
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${CONFIG_REPO_URL}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${CONFIG_SERVER_USERNAME}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${CONFIG_SERVER_PASSWORD}
    depends_on:
      registry-server:
        condition: service_healthy

  # API Gateway
  api-gateway:
    build: 
      context: ./apiGateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config-server

  # Auth Service
  auth-service:
    build: 
      context: ./authService
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/codefolio
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
      - config-server

  # Profile Service
  profile-service:
    build: 
      context: ./profileService
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/codefolio
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - GH_PAT=${GH_PAT}
    depends_on:
      - mysql
      - config-server

  # Contest Service
  contest-service:
    build: 
      context: ./contestService
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/codefolio
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
      - config-server

volumes:
  mysql_data: 