version: '3.8'

services:
  # Config Server
  config-server:
    build: ./configServer
    ports:
      - "${PORT:-8888}:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - codefolio-network

  # Registry Server (Eureka)
  registry-server:
    build: ./registryServer
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - config-server
    networks:
      - codefolio-network

  # API Gateway
  api-gateway:
    build: ./apiGateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=https://codefolio-config-server.onrender.com
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=https://codefolio-registry.onrender.com/eureka/
    networks:
      - codefolio-network

  # Auth Service
  auth-service:
    build: ./authService
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=https://codefolio-config-server.onrender.com
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=https://codefolio-registry.onrender.com/eureka/
    networks:
      - codefolio-network

  # Profile Service
  profile-service:
    build: ./profileService
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=https://codefolio-config-server.onrender.com
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=https://codefolio-registry.onrender.com/eureka/
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SPRING_DATASOURCE_URL=jdbc:mysql://root:QVzZzIIidBRQBBcAnpDvEeAESTFCvBtF@caboose.proxy.rlwy.net:42893/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=QVzZzIIidBRQBBcAnpDvEeAESTFCvBtF
    networks:
      - codefolio-network

  # Contest Service
  contest-service:
    build: ./contestService
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=https://codefolio-config-server.onrender.com
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=https://codefolio-registry.onrender.com/eureka/
    networks:
      - codefolio-network

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api-gateway:8080
      - REACT_APP_AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - REACT_APP_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - REACT_APP_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    depends_on:
      - api-gateway
    networks:
      - codefolio-network

networks:
  codefolio-network:
    driver: bridge

volumes:
  mysql-data: 