spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:mysql://localhost:3306/codefolio_profile
    username: root
    password: Root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0 # Random port for multiple instances

logging:
  level:
    com.codefolio.profileService: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# GitHub configuration