spring:
  application:
    name: profile-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0 # Random port for multiple instances

logging:
  level:
    com.codefolio.profileService: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://codefolio-registry.onrender.com/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# GitHub configuration
github:
  token: ${GITHUB_TOKEN} 