server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Profile Service Routes
        - id: profile-service-github
          uri: lb://profile-service
          predicates:
            - Path=/api/profiles/github/**
          filters:
            - StripPrefix=1

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profiles/**
          filters:
            - StripPrefix=1

        # Contest Service Routes
        - id: contest-service
          uri: lb://contest-service
          predicates:
            - Path=/api/contests/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: https://codefolio-registry.onrender.com/eureka/
  instance:
    prefer-ip-address: true 