spring:
  application:
    name: CONTEST-SERVICE
  mvc:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://dev-l4og12lsekqwkqbp.us.auth0.com/}

server:
  port: 8082

# Eureka Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

# API configurations
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000 