spring:
  application:
    name: PROFILE-SERVICE
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://codefolio-registry.onrender.com/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

# GitHub configuration
github:
  token: ${GITHUB_TOKEN}

# Logging Configuration
logging:
  level:
    com.codefolio.profileService: DEBUG 