spring:
  application:
    name: PROFILE-SERVICE
  mvc:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://code-folio-two.vercel.app}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://dev-l4og12lsekqwkqbp.us.auth0.com/}

server:
  port: 8083

# Eureka Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://codefolio-registry.onrender.com/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

# API configurations
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# GitHub API Configuration
github:
  api:
    base-url: https://api.github.com
    token: ${GITHUB_API_TOKEN} 