spring:
  application:
    name: PROFILE-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:codefolio_profile}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: ${PORT:8081}

# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

# GitHub configuration
github:
  token: ${GITHUB_TOKEN}

# Logging Configuration
logging:
  level:
    com.codefolio.profileService: INFO
  file:
    name: /var/log/codefolio/profile-service.log 