name: Deploy CodeFolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [configServer, registryServer, apiGateway, authService, profileService, contestService]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: |
        cd ${{ matrix.service }}
        ./mvnw clean package -DskipTests

    - name: Deploy to Cloud Platform
      env:
        CLOUD_PLATFORM_TOKEN: ${{ secrets.CLOUD_PLATFORM_TOKEN }}
      run: |
        # Add your cloud platform deployment commands here
        echo "Deploying ${{ matrix.service }}"

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Deploy Frontend to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        cd frontend
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 