name: Deploy CodeFolio

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy-registry-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      
      - name: Build Registry Server
        run: |
          cd registryServer
          ./mvnw clean package -DskipTests
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: codefolio-registry
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "registryServer"

  deploy-config-server:
    needs: deploy-registry-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      
      - name: Build Config Server
        run: |
          cd configServer
          ./mvnw clean package -DskipTests
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: codefolio-config
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "configServer"
        env:
          HD_SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${{ secrets.CONFIG_REPO_URL }}
          HD_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${{ secrets.EUREKA_URL }}

  deploy-services:
    needs: deploy-config-server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [apiGateway, authService, profileService, contestService]
        include:
          - service: apiGateway
            app_name: codefolio-gateway
          - service: authService
            app_name: codefolio-auth
          - service: profileService
            app_name: codefolio-profile
          - service: contestService
            app_name: codefolio-contest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      
      - name: Build ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          ./mvnw clean package -DskipTests
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ matrix.app_name }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "${{ matrix.service }}"
        env:
          HD_SPRING_CONFIG_IMPORT: ${{ secrets.CONFIG_SERVER_URL }}
          HD_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${{ secrets.EUREKA_URL }}

  deploy-frontend:
    needs: deploy-services
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Frontend to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd frontend
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 